models/RepairParts.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "repair_parts".
 *
 * @property integer $id
 * @property string $name
 * @property string $article
 * @property integer $deleted
 *
 * @property Boilers[] $boilers
 */
class RepairParts extends ActiveRecord
{
    public $image_file;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'repair_parts';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['deleted'], 'integer'],
            [['name', 'article'], 'string', 'max' => 255],
            [['name'], 'unique'],
            [['image_file'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Наименование',
       		'article' => 'Артикул',
            'image_file' => 'Изображение',
            'deleted' => 'Deleted',
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function afterSave($insert, $changedAttributes)
    {
    	parent::afterSave($insert, $changedAttributes);
    	
    	$relatedRecords = $this->getRelatedRecords();

    	// Save boilers
    	if ($this->isRelationPopulated('boilers')) {
    		$this->unlinkAll('boilers', true);
    		/** @var Boilers $boilers */
    		 foreach ($relatedRecords['boilers'] as $boiler) {
   				$this->link('boilers', $boiler);
    		}
    	}
    	
    	//Upload image_file
    	Files::upload($this, 'image_file');
    	
    	return true;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBoilers()
    {
        return $this->hasMany(Boilers::className(), ['id' => 'boilers_id'])->viaTable('repair_parts_boilers', ['repair_parts_id' => 'id'])->where(['deleted' => 0]);
    }
    
    /**
     * @param Boilers[] $boilers
     */
    public function setBoilers($boilers)
    {
    	$this->populateRelation('boilers', $boilers);
    }
    
    
    public static function getRepairPartsForOrder($order_id)
    {
        return RepairParts::find()
        ->leftJoin('repair_parts_boilers', 'repair_parts_boilers.repair_parts_id = repair_parts.id')
        ->leftJoin('clients', 'clients.id = :order_id', ['order_id' => $order_id])
        ->leftJoin('orders', 'clients.boiler_id = repair_parts_boilers.boilers_id')
        ->where(['repair_parts.deleted' => 0, 'orders.id' => $order_id])
        ->orderBy('name');
    }
    
    public static function getRepairPartsForBoiler($boiler_id, $specialist_id = null)
    {
        return RepairParts::find()
            ->leftJoin('repair_parts_boilers', 'repair_parts_boilers.repair_parts_id = repair_parts.id')
            ->leftJoin('store_remains', 'store_remains.repair_part_id = repair_parts.id')
            ->where(['repair_parts.deleted' => 0, 'repair_parts_boilers.boilers_id' => $boiler_id])
//            ->andWhere(['!=', 'store_remains.quantity', 0])
            ->andFilterWhere(['store_remains.specialist_id' => $specialist_id])
            ->orderBy('name');
    }
    
    public function getAmount()
    {
        if (($store_remain = StoreRemains::findOne(['specialist_id'=>null, 'repair_part_id'=>$this->id, 'deleted'=>0])) !== null)
            return $store_remain->sell_amount;
        else
            return 0;
    }
}

controllers/OrdersController.php
<?php

namespace app\controllers;

use app\managers\OrderManager;
use app\models\forms\ArrearsPayments;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\ForbiddenHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;
use app\models\Orders;
use app\models\OrderRepairParts;
use app\models\OrderTransports;
use app\models\OrderServices;
use yii\data\ActiveDataProvider;
use app\models\OrdersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Users;

/**
 * OrdersController implements the CRUD actions for Orders model.
 */
class OrdersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
				   [
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Orders models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $this->view->title = 'Все заказы';

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Orders model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
    	$dataOrderRepairParts= new ActiveDataProvider([
    			'query' => OrderRepairParts::find()->where(['order_id' => $id, 'deleted' => 0]),
    	]);
    	
    	$dataOrderTransports= new ActiveDataProvider([
    			'query' => OrderTransports::find()->where(['order_id' => $id, 'deleted' => 0]),
    	]);
    	
    	$dataOrderServices= new ActiveDataProvider([
    			'query' => OrderServices::find()->where(['order_id' => $id, 'deleted' => 0]),
    	]);

        $arrearsPaymentModel = new ArrearsPayments(['orderId' => $id]);


    	return $this->render('view', [
            'model' => $this->findModel($id),
   			'dataOrderRepairParts' => $dataOrderRepairParts,
    		'dataOrderTransports' => $dataOrderTransports,
    		'dataOrderServices' => $dataOrderServices,
            'arrearsPaymentModel' => $arrearsPaymentModel,
        ]);
    }

    /**
     * Присваивает заказ авторизованному пользователю (специалисту)
     * @param $order_id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionTakeOrder($order_id)
    {
        $model = $this->findModel($order_id);
        $took = (new OrderManager(['order' => $model]))->takeOrder()->changeStatus(Orders::STATUS_WORK)->saveOrder(false);

        if($took){
            Yii::$app->session->setFlash('success', 'Вы взяли заказ');
            return $this->redirect(['view', 'id' => $order_id]);
        } else {
            Yii::$app->session->setFlash('error', 'Во время исполнения произошла ошибка');
            return $this->redirect(['view', 'id' => $order_id]);
        }
    }

    /**
     * Фиксирует оплату по заказу от кого-то на "баланс" текущего пользователя
     * @param $order_id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionGetPayment($order_id)
    {
        $model = $this->findModel($order_id);
        $got = (new OrderManager(['order' => $model]))->userGotPayment()->saveOrder(false);

        if($got){
            Yii::$app->session->setFlash('success', 'Вы зафиксировали оплату');
            return $this->redirect(['view', 'id' => $order_id]);
        } else {
            Yii::$app->session->setFlash('error', 'Во время исполнения произошла ошибка');
            return $this->redirect(['view', 'id' => $order_id]);
        }
    }

    /**
     * Creates a new Orders model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @throws ForbiddenHttpException
     * @return mixed
     */
    public function actionCreate()
    {
        if(Yii::$app->user->identity->permission === Users::PERMISSION_ADVERTISING)
        {
            throw new ForbiddenHttpException('Доступ запрещен');
        }

    	$model = new Orders();
    	
    	if ($model->load(Yii::$app->request->post())) {
    	    if (Yii::$app->request->isAjax) {
    	        Yii::$app->response->format = Response::FORMAT_JSON;
    	        return ActiveForm::validate($model);
    	    }
    	    
    	    if($model->save()) {
    	        return $this->redirect(['index']);
    	    }
    	} else {
    	    $model->client_id = ArrayHelper::getValue(Yii::$app->request->get(), 'client_id');
    	    return $this->renderAjax('create', [
    	        'model' => $model,
    	    ]);
    	}
    }

    /**
     * Updates an existing Orders model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        if(Yii::$app->user->identity->permission === Users::PERMISSION_ADVERTISING)
        {
            throw new ForbiddenHttpException('Доступ запрещен');
        }

        $model = $this->findModel($id);

    	if ($model->load(Yii::$app->request->post())) {
    	    if (Yii::$app->request->isAjax) {
    	        Yii::$app->response->format = Response::FORMAT_JSON;
    	        return ActiveForm::validate($model);
    	    }
    	    
    	    if($model->save()) {
    	        return $this->redirect(['view', 'id' => $model->id]);
    	    }
    	}

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Orders model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionDelete($id)
    {

    	$model = $this->findModel($id);
    	$model->deleted = 1;
    	$model->save();

        return $this->redirect(Yii::$app->request->referrer);
    }
    
    /**
     * Finds the Orders model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Orders the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Orders::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
	 public function print_arr($array) {
        echo '<pre>'.print_r($array, true).'</pre>';
    }

    /**
     * Меняет статус заказа на "В работе"
     * @param int $id ID заказа
     * @return Response
     * @throws NotFoundHttpException
     */
    public function actionAcceptOrder($id)
    {
        $model = $this->findModel($id) ?? null;

        if ($model){
            $model->status = Orders::STATUS_WORK;
            if (!$model->save()){
                Yii::error($model->errors, '_error');
                Yii::$app->session->setFlash('error', 'Ошибка изменения статуса заказа');
            } else {
                Yii::$app->session->setFlash('success', 'Заказ принят в работу');
            }
        }
        return $this->redirect(['view', 'id' => $model->id]);
    }
}

views/orders/_form.php
<?php

use kartik\date\DatePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Clients;
use app\models\Specialists;
use app\models\Boilers;
use yii\bootstrap\Modal;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Orders */
/* @var $form yii\widgets\ActiveForm */

$filter_url = \Yii::$app->getUrlManager()->createUrl('specialists/filter');
$this->registerJs("
$('#orders-client_id').on('change',function () {
    $.ajax({
        url: '$filter_url',
        type: 'POST',
        data: { client_id: $('#orders-client_id').val() },
        success: function(data) {
            var data_arr = eval('(' + data + ')');
            var select = $('#orders-specialist_id');
            select.find('option').remove();
            $('<option>').val('').text('Выберите вариант').appendTo(select);
            $.each(data_arr, function(key, value) {
                $('<option>').val(value.id).text(value.name).appendTo(select);
            });
        }
    });
});
");

?>

    <div class="orders-form">

<?php $form = ActiveForm::begin([
    'id' => 'order-form',
    'enableAjaxValidation' => true,
]); ?>

    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6 vcenter">
            <?= $form->field($model, 'client_id')->widget(Select2::className(), [
                'data' => ArrayHelper::map(Clients::find()->where(['deleted' => 0])->orderBy(['name' => SORT_ASC])->asArray()->all(),
                    'id', 'name'),
                'theme' => \kartik\select2\Select2::THEME_DEFAULT,
                'options' => [
                    'prompt' => 'Выберите вариант',
                ],
            ]) ?>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6 vcenter">
            <?= $form->field($model, 'estimate')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 vcenter">
            <?= $form->field($model, 'boiler_id')->widget(Select2::className(), [
                'data' => Boilers::getBoilersDropdown(),
                'options' => [
                    'prompt' => 'Выберите вариант',
                ],
            ]) ?>
        </div>
    </div>
    <div class="row">
        <?php if (Yii::$app->user->identity->permission === \app\models\Users::PERMISSION_SPECIALIST) { ?>
            <div class="col-md-12 col-sm-12 col-xs-12 vcenter">
                <?= $form->field($model, 'advert_source_id')->widget(Select2::className(), [
                    'data' => ArrayHelper::map(\app\models\Users::find()->advertising()->all(), 'id', 'name'),
                    'theme' => \kartik\select2\Select2::THEME_DEFAULT,
                    'options' => [
                        'prompt' => 'Выберите вариант',
                    ],
                ]) ?>
            </div>
        <?php } else { ?>
            <div class="col-md-6 col-sm-6 col-xs-6 vcenter">
                <?= $form->field($model, 'specialist_id')->widget(Select2::className(), [
                    'data' => ArrayHelper::map(Specialists::getSpecialistsForBoiler($model->boiler_id)->all(),
                        'id', 'name'),
                    'value' => $model->specialist_id,
                    'theme' => \kartik\select2\Select2::THEME_DEFAULT,
                    'options' => [
                        'prompt' => 'Выберите вариант',
                        'disabled' => $model->isNewRecord,
                    ],
                ]) ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6 vcenter">
                <?= $form->field($model, 'advert_source_id')->widget(Select2::className(), [
                    'data' => ArrayHelper::map(\app\models\Users::find()->advertising()->orderBy(['name' => SORT_ASC])->all(),
                        'id', 'name'),
                    'theme' => \kartik\select2\Select2::THEME_DEFAULT,
                    'options' => [
                        'prompt' => 'Выберите вариант',
                    ],
                ]) ?>
            </div>
        <?php } ?>
    </div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12 vcenter">
            <?= $form->field($model, 'deferred_to')->widget(DatePicker::className(), [
                'value' => date('d-M-Y', strtotime('+2 days')),
                'options' => [
                    'placeholder' => 'Выберите дату',
                    'autocomplete' => 'off',
                ],
                'pluginOptions' => [
                    'format' => 'yyyy-mm-dd',
                    'todayHighlight' => true
                ]
            ]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить',
            ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>


<?php
Modal::begin([
    'header' => 'Элемент расходов',
    'id' => 'modal',
    'size' => 'modal-lg',
]);
echo "<div id='modal-content'>Загружаю...</div>";
Modal::end();


Modal::begin([
    'header' => 'Элемент расходов',
    'id' => 'modal-second',
    'size' => 'modal-lg',
]);
echo "<div id='modal-content'>Загружаю...</div>";
Modal::end();
?>
<?php
$script = <<<JS
    $(document).ready(function(){
        $(document).on('change', '#orders-boiler_id', function(){
            var boiler_id = $(this).val();
            var client_id = $('#orders-client_id').val();
            var spec_dropdown = $("#orders-specialist_id");
            $.get(
                '/specialists/get-list-by-boiler-and-client',
                {
                    boiler: boiler_id,
                    client: client_id
                },
                function(response) {
                    if (response !== 'error'){
                         spec_dropdown.removeAttr("disabled");
                         spec_dropdown.html(response);
                    }
                }
            );
        })
    })
JS;
$this->registerJs($script);

views/orders/_form_arrears_payment.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\Users;

/**
 * @var \app\models\forms\ArrearsPayments $model
 * @var \app\models\Users $user
 * @var \app\models\Orders $order
 * @var double $maxSpecialistPayment
 * @var double $maxAdvertisingPayment
 */

?>

<?php $form = ActiveForm::begin(['action' => Url::toRoute(['cashbook/pay-arrears']), 'enableClientValidation' => false]); ?>

    <?= $form->field($model, 'orderId')->label(false)->hiddenInput() ?>

    <?php if($user->permission === Users::PERMISSION_ADMIN): ?>
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">Дата</label>
                <input type="text" class="form-control" name="" disabled="" value="<?=date('d.m.Y')?>">
            </div>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'advertisingPayment')->input('number', ['max' => $maxAdvertisingPayment]) ?>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">Дата</label>
                <input type="text" class="form-control" name="" disabled="" value="<?=date('d.m.Y')?>">
            </div>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'specialistPayment')->input('number', ['max' => $maxSpecialistPayment]) ?>
        </div>
    <?php endif; ?>
    <?php if($user->permission === Users::PERMISSION_SPECIALIST): ?>
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">Дата</label>
                <input type="text" class="form-control" name="" disabled="" value="<?=date('d.m.Y')?>">
            </div>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'adminPayment')->input('number', ['max' => Yii::$app->user->identity->orderResponsibility->getAdminArrears($order)]) ?>
        </div>
    <?php endif; ?>

    <div class="col-md-12 text-center">
        <?= Html::submitButton('Внести задолжность', ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>

views/orders/_form_view.php
<?php

use app\models\Orders;
use app\models\Users;

/* @var $this yii\web\View */
/* @var $model app\models\Orders */

?>

<div class="col-md-4">
    <div class="form-group">
        <label class="control-label">Клиент</label>
        <input type="text" class="form-control" disabled="" name="" value="<?= $model->client->name ?>">
    </div>
</div>
<div class="col-md-4">
    <div class="form-group">
        <label class="control-label">Обшая стоимость заказа</label>
        <input type="text" class="form-control" disabled="" name="" value="<?= number_format($model->amount, 2) ?>">
    </div>
</div>
<div class="col-md-4">
    <div class="form-group">
        <label class="control-label">Скидка %</label>
        <input type="text" class="form-control" disabled="" name="" value="<?= $model->estimate ?>">
    </div>
</div>
<div class="col-md-4">
    <div class="form-group">
        <label class="control-label">Адрес</label>
        <input type="text" class="form-control" disabled="" name="" value="<?= $model->client->address ?>">
    </div>
</div>
<div class="col-md-4">
    <div class="form-group">
        <label class="control-label">Специалист</label>
        <input type="text" class="form-control" disabled="" name=""
               value="<?= $model->specialist ? $model->specialist->name : '' ?>">
    </div>
</div>
<div class="col-md-4">
    <div class="form-group">
        <label class="control-label">Источник рекламы</label>
        <input type="text" class="form-control" disabled="" name=""
               value="<?= $model->advertSource ? $model->advertSource->name : '' ?>">
    </div>
</div>
<div class="col-md-4">
    <div class="form-group">
        <label class="control-label">Котел</label>
        <input type="text" class="form-control" disabled="" name=""
               value="<?= $model->boiler ? $model->boiler->model : '' ?>">
    </div>
</div>
<?php if (Yii::$app->user->identity->permission != Users::PERMISSION_SPECIALIST) { ?>
    <div class="col-md-4">
        <div class="form-group">
            <label class="control-label">Регион</label>
            <input type="text" class="form-control" disabled="" name=""
                   value="<?= $model->client->city ? $model->client->city->name : '' ?>">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label class="control-label">Дата создания</label>
            <input type="text" class="form-control" disabled="" name="" value="<?= $model->created_at ?>">
        </div>
    </div>
<?php } else { ?>
    <div class="col-md-8">
        <div class="form-group">
            <label class="control-label">Дата создания</label>
            <input type="text" class="form-control" disabled="" name="" value="<?= $model->created_at ?>">
        </div>
    </div>
<?php } ?>
<div class="col-md-4">
    <div class="form-group">
        <label class="control-label">Создал</label>
        <input type="text" class="form-control" disabled="" name="" value="<?= $model->createdBy->name ?>">
    </div>
</div>
<div class="col-md-8">
    <div class="form-group">
        <label class="control-label">Статус</label>
        <input type="text" class="form-control" disabled="" name=""
               value="<?= Orders::getStatusList()[$model->status] ?>">
    </div>
</div>
<div class="col-md-12">
    <div class="form-group">
        <label class="control-label">Комментарий</label>
        <textarea class="form-control" disabled="" value=""><?= $model->comment ?></textarea>
    </div>
</div>

views/orders/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Cities;
use app\models\Specialists;
use app\models\Clients;
use app\models\Boilers;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\OrdersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="orders-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
    
	<div class="row">
        <div class="hidden">
            <?= $form->field($model, 'status')->hiddenInput()->label(false) ?>
        </div>
		<div class="col-md-2 vcenter">
		    <?= $form->field($model, 'city_id')->dropDownList(ArrayHelper::map(Cities::find()->where(['deleted' => 0])->asArray()->all(), 'id', 'name'),
		      ['prompt' => 'Выберите вариант']) ?> 
		</div>
		<div class="col-md-2 vcenter">
    		<?= $form->field($model, 'specialist_id')->dropDownList(ArrayHelper::map(Specialists::find()->where(['deleted' => 0])->orderBy(['name' => SORT_ASC])->asArray()->all(), 'id', 'name'),
		      ['prompt' => 'Выберите вариант']) ?>
		</div>
		<div class="col-md-2 vcenter">
    		<?= $form->field($model, 'client_id')->widget(Select2::class, [
                'data' => ArrayHelper::map(Clients::find()->where(['deleted' => 0])->orderBy(['name' => SORT_ASC])->asArray()->all(), 'id', 'name'),
                'pluginOptions' => [
                    'allowClear' => true,
                    'placeholder' => 'Выберите клиента'
                ],
            ]) ?>
		</div>
		<div class="col-md-2 vcenter">
    		<?= $form->field($model, 'boiler_id')->dropDownList(Boilers::getBoilersDropdown(),
		      ['prompt' => 'Выберите вариант']) ?>
		</div>
		<div class="col-md-2 vcenter">
		    <div class="form-group">
		    	<div><label class="control-label">&nbsp;</label></div>	
        		<?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
        		<?= Html::a('<i class="fa fa-times"></i>', ['index'], ['class' => 'btn btn-white']) ?>
    		</div>
		</div>
	</div>
			
    <?php ActiveForm::end(); ?>

</div>

views/orders/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Orders */

$this->title = 'Добавить ';
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-create">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/orders/index.php
<?php

use app\models\Orders;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use app\models\Users;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $searchModel \app\models\OrdersSearch */

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-index">

    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title"><?=$this->title?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->render('_search', ['model' => $searchModel]); ?>
                <?php if(Yii::$app->user->identity->permission != Users::PERMISSION_ADVERTISING): ?>
                    <p>
                        <?= Html::a('<i class="fa fa-plus"></i> Добавить', ['create'], [
                            'data-target'=>'/orders/create',
                            'class' => 'btn btn-success','onClick'=>"
                        $('#modal').modal('show')
                        .find('#modal-content')
                        .load($(this).attr('data-target'));
                        return false;"])
                        ?>
                    </p>
                <?php endif; ?>
            <?php
            try {
                echo GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        'created_at',
                        [
                            'attribute' => 'client_id',
                            'content' => function ($data) {
                                if ($data->client) {
                                    return $data->client->name;
                                }
                                return null;
                            },
                        ],
                        [
                            'attribute' => 'boiler_id',
                            'content' => function (Orders $data) {
                                if ($data->boiler) {
                                    return $data->boiler->brand->name . ' ' . $data->boiler->model;
                                }
                                return null;
                            },
                        ],
                        [
                            'attribute' => 'specialist_id',
                            'value' => 'specialist.name',
                            'visible' => Yii::$app->user->identity->permission != Users::PERMISSION_SPECIALIST,
                        ],
                        [
                            'attribute' => 'advert_source_id',
                            'content' => function (Orders $data) {
                                if ($data->advertSource) {
                                    return $data->advertSource->name;
                                }
                                return null;
                            },
                        ],
                        //'amount',
                        [
                            'attribute' => 'amount',
                            'content' => function ($data) {
                                return number_format($data->amount, 2);
                            },
                        ],
                        //'estimate',
                        //'address',
                        // 'specialist_id',
                        // 'advert_source_id',
                        // 'boiler_id',
                        // 'city_id',
                        //'deferred_to',
                        // 'comment',
                        // 'created_by',
                        // 'status',
                        [
                            'attribute' => 'city_id',
                            'value' => 'client.city.name',
                            'visible' => Yii::$app->user->identity->permission != Users::PERMISSION_SPECIALIST,
                        ],
                        [
                            'attribute' => 'status',
                            'content' => function (Orders $data) {
                                return $data::getStatusList()[$data->status];
                            },
                        ],
                        [
                            'class' => 'yii\grid\ActionColumn',
                            'template' => '{view} {delete}',
                            'controller' => 'orders',
                            //                        'urlCreator' => function ($action, $model, $key, $index) {
                            //                            return \yii\helpers\Url::toRoute([Yii::$app->controller->id.'/'.$action, 'id' => $model->id]);
                            //                        },
                            'buttons' => [
                                'view' => function ($url, $model, $key) {
                                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', [$url],
                                        ['style' => 'margin-right: 10px;']);
                                },
                            ],
                        ],
                        // ['class' => 'yii\grid\ActionColumn'],
                    ],
                ]);
            } catch (Exception $e) {
                Yii::error($e->getMessage(), '_error');
            } ?>
        </div>
    </div>
</div>
        <?php
    Modal::begin([
        'header' => 'Заказ',
        'id' => 'modal',
        'options' => [
            'tabindex' => false,
        ],
        'size'=>'modal-lg',
    ]);
    echo "<div id='modal-content'>Загружаю...</div>";
    Modal::end();
    ?>